name: Artifacts (Package)
on:
  workflow_dispatch:
jobs:
  mingw64-gcc:
    name: MinGW GCC

    runs-on: windows-2022
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: "Setup"
        run: |
          make


      - name: Upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
         name: apimon
         path: build
         if-no-files-found: error
